version: '3'

services:
  backend:
    image: blance97/dataechoserver-backend:latest
    ports:
      - "3000:3000"
      - "3001:3001"

  frontend:
    image: blance97/dataechoserver-frontend:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend