apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataechoserver-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: blance97/dataechoserver-backend:latest
          ports:
            - containerPort: 3000
            - containerPort: 8081
