apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
    - name: ws
      port: 8081
      targetPort: 8081
  type: ClusterIP
