name: 'Backend CD'
on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/backend-cd.yml'
      - '.github/workflows/backend-ci.yml'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Extract short SHA
        id: extract_sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push backend
        uses: docker/build-push-action@v5 # Added this line
        with:
          context: ./backend
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/dataechoserver-backend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/dataechoserver-backend:${{ steps.extract_sha.outputs.sha_short }}
      - name: Bump version and push changes
        run: |
          cd backend
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git push