name: 'Backend CD'
on:
  push:
    branches:
      - main
    paths:
        - 'backendNode/**'
        - '.github/workflows/backend-cd.yml'
        - '.github/workflows/backend-ci.yml'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: extract short SHA
        id: extract_sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push EchoServerReact
        uses: docker/build-push-action@v2
        with:
          context: ./EchoServerReact
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/dataechoserver-backend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/dataechoserver-backend:${{ steps.extract_sha.outputs.short_sha }}

      - name: Bump version and push changes
        if: github.event.pull_request.merged == true
        run: |
          cd backendNode
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          npm version patch -m "Bump version to %s"
          git push
