name: Docker Publish
on:
  push:
    branches:
      - main
      - master
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backendNode
        uses: docker/build-push-action@v2
        with:
          context: ./backendNode
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/dataechoserver-backend:latest,${{ secrets.DOCKERHUB_USERNAME }}/dataechoserver-backend:${{ github.sha }}

      - name: Build and push EchoServerReact
        uses: docker/build-push-action@v2
        with:
          context: ./EchoServerReact
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/dataechoserver-frontend:latest,${{ secrets.DOCKERHUB_USERNAME }}/dataechoserver-frontend:${{ github.sha }}

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.26.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch