name: Frontend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'EchoServerReact/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install dependencies for EchoServerReact
        run: |
          cd EchoServerReact
          npm install
      - name: Build EchoServerReact
        run: |
          cd EchoServerReact
          npm run build
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push EchoServerReact
        uses: docker/build-push-action@v2
        with:
          context: ./EchoServerReact
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/dataechoserver-frontend:latest,${{ secrets.DOCKERHUB_USERNAME }}/dataechoserver-frontend:${{ github.sha }}
      - name: Bump version and push changes
        run: |
          cd EchoServerReact
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          npm version patch -m "Bump version to %s"
          git push