name: Frontend CI

on:
  push:
    branches:
      - main
    paths:
      - '../../frontend/**'
      - '.github/workflows/frontend-cd.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install dependencies for frontend
        run: |
          cd frontend
          npm install
      - name: Run tests for frontend
        run: |
          cd frontend
          npm run test -- --watchAll=false