apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dataechoserver
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/blance97/DataEchoServer.git
    targetRevision: main
    path: k8s-manifest
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true